# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNFirebaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseApp
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'

  target 'RNFirebaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNFirebaseApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseApp-tvOS

  target 'RNFirebaseApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
